[package]
name = "cmtool-example"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true


[dependencies]
cmtool-data.workspace = true
nalgebra.workspace = true
nalgebra-sparse = "0.11.0"
ndarray = "0.16.1"

[[example]]
path = "src/mixing_simple.rs"
name = "mixing_simple"
