<!--
 SPDX-License-Identifier: GPL-3.0-or-later
-->
<xs:schema
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="2"
>
    <xs:include schemaLocation="units.xsd" />
    <xs:include schemaLocation="connections.xsd" />
    <xs:include schemaLocation="reactors.xsd" />

    <xs:element name="Root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Reactors" type="Reactors" minOccurs="1" />
                <xs:element
                    name="Connections"
                    type="Connections"
                    minOccurs="0"
                />
                <xs:element name="Feeds" type="Feeds" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="run_id" type="xs:string" use="required" />
            <xs:attribute name="version" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>
