[book]
authors = ["Casale Benjamin"]
language = "en"
src = "src"
title = "Compartment Modeling Tool"
# heading-split-level = 4

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.bib]
bibliography = "refs.bib"
backend = "csl"
csl-style = "apa"
title = "References"


[output.html]
mathjax-support = true


[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false
runnable = false
