[package]
name = "cmtool-core"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
[dependencies]
cmtool-data.workspace = true
enum_dispatch.workspace = true
thiserror.workspace = true


vtkio = { version = "0.6.3", optional = true }

[features]
use_vtk = ["vtkio"]
