[package]
name = "cmtool"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
[dependencies]
clap.workspace = true
cmtool-core.workspace = true
cmtool-data.workspace = true
cmtool-assemble.workspace = true
thiserror.workspace = true
nalgebra.workspace = true
nalgebra-sparse.workspace=true

[features]
use_vtk = ["cmtool-core/use_vtk"]


[lib]
path = "src/lib.rs"
